### ISSUE TITLE
Container image list for inclusion in helm charts

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1019]
## Acceptance Criteria

- implemented in ruby
- has unit tests
- can be based on the [current implementation](https://github.com/cloudfoundry-incubator/kubecf/blob/master/rules/kubecf/image_list.tmpl.rb)
- should accept a list of combinations for which the image list must be generated:
e.g.
```
combinations:
- this.is.a.flag: value1
  another.flag: foo
- this.is.a.flag: value2
  another.flag: bar
```
