### ISSUE TITLE
 Configurable multi-stack support

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1086]
# Acceptance Criteria

- [X] Implement proposal and get it merged (done in #1202)
- [ ] Update documentation about bumping buildpacks (and cf-deployment). Should have been part of #1202 but wasn't.
- [X] BLOCKER Update pipelines that bump stemcells and buildpacks to update the new locations
- [ ] Create issue to write tests, both for templating logic and for the validating schema
- [X] Create a proposal for imagePullSecrets support: #1421
- [ ] Create issue to review current configuration options and create guidelines for creating new settings

# Configurable multi-stack support in KubeCF

Currently KubeCF supports 2 builtin stacks, the upstream `cflinuxfs3` stack, and the SUSE `sle15` stack.

Definitions for the stacks are distributed over many files, with additional files required for each buildpack for each stack. This makes adding or replacing a stack tedious work that essentially creates a fork unless the new stack definitions are merged into the core KubeCF sources.

This text tries to prescribe a mechanism to define stacks in a declarative way, so that they can be added to a KubeCF release without requiring changes to the core chart itself at all.

## Goals

* Builtin stacks are built into the charts and not defined by `values.yaml`.

* Builtin stacks can be updated at deployment time with newer root filesystems and buildpacks.

* Buildpacks can be added to and removed from builtin stacks; the install order can be changed.

* Additional stacks can be declared at deployment time without having to modify the helm chart.

## Declaration in `values.yaml`

```yaml
stacks: [mystack, sle15, cflinuxfs3]

stack:
  mystack:
    description: There are many stacks, but this one is mine!
    registry:
      url: registry.example.com:5000/my-org
      username: ~
      password: ~
    rootfs_image: sle15-release:SLE_15_SP1-25.2-7.0.0_374
    # The eirini_rootfs_image is embedded in the bits-release image and cannot be configured.
    buildpack_list: [ruby]
    buildpacks:
      ruby:
        image: suse-ruby-buildpack:SLE_15_SP1-25.2-7.0.0_374.gb8e8e6af
        file: suse-ruby-buildpack/packages/ruby-buildpack-sle15/ruby-buildpack-sle15-v1.8.19.1-1.1-63c0bb58.zip
  sle15:
    buildpack_list: [+, newlang]
    buildpacks:
      newlang:
        ...
```

Only the stacks listed in `stacks` will be configured, and the first stack in that list will be the default stack.

The `stack` key contains the definitions for additional stacks, or updates to the builtin ones.

It is assumed that all images for a single stack will be loaded from the same registry.

The order of installation is defined by the `buildpack_list`. For builtin stacks, the `+` sign can be used to merge with the builtin buildpack list. `[lang1, +, lang2]` will prepend `lang1-buildpack` to the beginning, and append `lang2-buildpack` at the end of the builtin list.

It should be possible to create all required ops-file logic for dynamic stack configuration from these settings using templating logic.

### Eirini rootfs is not configurable

Right now the rootfs for Eirini is pre-loaded inside the `bits` image and cannot be configured at deployment time. Eirini also does not yet have multi-stack support, so only a single stack image will be available.

Extending Eirini with multi-stack support seems to be a larger effort and will probably not be available in the very near future (needs a champion). But if it does materialize then the eirini rootfs image definition can easily be added to the structure above.

### Buildpacks are unrelated to stemcells

The buildpacks should not include a stemcell name in their tags. The stemcell can even be a different OS than the rootfs.

E.g. the `sle15` Ruby buildpack defined above should just be called `suse-ruby-buildpack:1.8.19.1`.

There will be a separate proposal expanding on this.

### Buildpack filenames should be standardized

There is no good reason why the `file` path must be specified explicitly. The CI building the releases should use the upstream naming convention and put the ZIP into: `packages/$LANG-buildpack-$STACK/$LANG-buildpack-$STACK-v$VERSION.zip` based on a buildpack definition like:

```yaml
stack:
  $STACK:
    buildpacks:
      $LANG: my-buildpack:$VERSION
```

The old format will continue to be supported for backwards compatibility.

## Deprecations

The settings for `features.suse_buildpacks` and `features.suse_stack` will go away. The KubeCF helm chart should throw an error if these are still defined, to prevent errors during upgrades.
