### ISSUE TITLE
Ops file changes not being applied

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1183]
### This bug is probably already fixed.

**Describe the bug**
Upon applying an ops file (to update anti-affinity rules for pods), the changes were not being propagated to QuarksStatefulSets correctly.

This may have already been fixed; filing to schedule reproduction and documentation if necessary.

**To Reproduce**
We had a deployment of KubeCF with pod anti-affinity rules set for diego-cell:

<details><summary>ops file</summary>

```yaml
operations:
  inline:
  - type: replace
    path: /instance_groups/name=diego-cell/env?/bosh/agent/settings/affinity
    value:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: quarks.cloudfoundry.org/quarks-statefulset-name
                operator: In
                values:
                - diego-cell
            topologyKey: kubernetes.io/hostname
          weight: 100
```
</details>

We changed it to `requiredDuringSchedulingIgnoredDuringExecution` (with appropriate fixes to drop the `podAffinityTerm` part).

Upon applying the changes, the ops files were merged into the config map (and the `with-ops` secret), but the change was not propagated into the QuarksStatefulSet.

**Expected behavior**
The changes apply to the QuarksStatefulSet / StatefulSet / pods.

**Environment**
 - KubeCF 2.2.2
 - EKS

**Additional context**
Was unable to reproduce this in `master`; it's possible that one of the operator bumps has fixed this already.  This needs to be reproduced and documented if it's an actual issue.
