### ISSUE TITLE
Always use a hostpath storage class for diego cells

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1241]
**Is your feature request related to a problem? Please describe.**
The diego cell volume is host to application data that changes often and seems to cause problems with storage classes based on NFS.
Other storage classes, such as the ones on EKS can also present problems.

**Describe the solution you'd like**
Given that the recommended way to deploy diego cells on Kubernetes clusters is to tie them 1-to-1 to Kube Nodes, we should, by default, always use a hostpath storage class for the cell volumes. The option to override the storage class used for the cell should still be available.

Example storage class:

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: diego-cell-sc
provisioner: example.com/hostpath
parameters:
  path: /tmp
```
