### ISSUE TITLE
Double vertical bars "|" when interpolate external database CA cert

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry-incubator/kubecf#1250]
My values.yaml to enable external database:
```
features:
  external_database:
    require_ssl: true
    ca_cert: "-----BEGIN CERTIFICATE-----\nMIIEZTCCAs2gAwIBAgIQcmIWPjyzmV7KIlkHxqSpDjANBgkqhkiG9w0BAQsFADA8\nMQwwCg...fTPSqHY+1Y7tM0Qf\nLc6UF7wkJjfDdllkDNBl3yOJAluL2KMFsg==\n-----END CERTIFICATE-----\n"
    enabled: true
    type: postgres
    host: <my_host>
    port: 5524
    databases:
      uaa:
        name: uaa
        password: <uaa_password>
        username: <uaa_username>
      cc:
        name: cloud_controller
        password: <cc_password>
        username: <cc_username>
      bbs:
        name: diego
        password: <diego_password>
        username: <diego_username>
      routing_api:
        name: routing-api
        password: <routing_api_password>
        username: <routing_api_username>
      policy_server:
        name: network_policy
        password: <network_policy_password>
        username: <network_policy_username>
      silk_controller:
        name: network_connectivity
        password: <network_connectivity_password>
        username: <network_connectivity_username>
      locket:
        name: locket
        password: <locket_password>
        username: <locket_username>
      credhub:
        name: credhub
        password: <credhub_password>
        username: <credhub_username>
```

After helm install kubecf, when check the manifest.yaml via 
```
kubectl get secrets -n kubecf desired-manifest-v1 -o json | jq --raw-output '.data["manifest.yaml"]' | base64 --decode > cf.yaml
```
there are two vertical bars `|` at the beginning of every interpolated external db CA cert like this:
```
        ca_certs:
        - |
          |
            -----BEGIN CERTIFICATE-----
            MIIEZTCCAs2gAwIBAgIQcmIWPjyzmV7KIlkHxqSpDjANBgkqhkiG9w0BAQsFADA8
            ...
            Lc6UF7wkJjfDdllkDNBl3yOJAluL2KMFsg==
            -----END CERTIFICATE-----
```

So the CA cert can't be recognized as a valid cert.

Would you please fix this issue? Maybe the `|` bar at lines like https://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/assets/operations/instance_groups/database.yaml#L262 needs to be removed.
