### ISSUE TITLE
database: PXC does not pick up new database root password

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/kubecf#1355]
**Describe the bug**
When we change the `var-pxc-root-password` secret and restart the `database` pod(s), the root database does not get updated; this means:
- The readiness probe will never pass, as it is using the new, modified password instead.
- Any database seeder pods will fail, as they are attempting to use the new root password.

**To Reproduce**
1. Deploy on minikube with internal database.
2. Apply the following secret rotation config map:
<details><summary><code>rotate.pxc-root-password.yaml</code></summary>

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    quarks.cloudfoundry.org/secret-rotation: "true"
  name: rotate.pxc-root-password
  namespace: kubecf
data:
    secrets: '[ "var-pxc-root-password" ]'
```
</details>
3. Delete the <tt>database-0</tt> pod and let it restart.

**Expected behaviour**
The database root password is changed.

**Actual behaviour**
The database root password stays the same; the readiness probe no longer passes.

**Environment**
 - KubeCF ~ d192fa2f97033f8c9cd83dbb7dac1d2f8caed012

**Additional context**
Found in the context of #703
