### ISSUE TITLE
Missing CF info API values

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1367]
We are not filling the API info values.

Example:
Hitting http://api.vic-cap.ci.kubecf.charmedquarks.me/info  I only get
```
{
  "name": "",
  "build": "",
  "support": "",
  "version": 0,
  "description": "",
  "authorization_endpoint": "https://login.vic-cap.ci.kubecf.charmedquarks.me",
  "token_endpoint": "https://uaa.vic-cap.ci.kubecf.charmedquarks.me",
  "allow_debug": true
}

```

It should look like: (from https://apidocs.cloudfoundry.org/268/info/get_info.html)
```
{
  "name": "vcap",
  "build": "2222",
  "support": "http://support.cloudfoundry.com",
  "version": 2,
  "description": "Cloud Foundry sponsored by Pivotal",
  "authorization_endpoint": "http://localhost:8080/uaa",
  "token_endpoint": "http://localhost:8080/uaa",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "api_version": "2.89.0",
  "app_ssh_endpoint": "ssh.system.domain.example.com:2222",
  "app_ssh_host_key_fingerprint": "47:0d:d1:c8:c3:3d:0a:36:d1:49:2f:f2:90:27:31:d0",
  "app_ssh_oauth_client": null,
  "routing_endpoint": "http://localhost:3000",
  "logging_endpoint": "ws://loggregator.vcap.me:80"
}
```
This is consumed and shown in Stratos.

This would also be changed and consumed downstream, too, so if possible it needs to be able to change without recreating a bosh release.

**Comment by ShuangMen** [comment]
I try to curl different api versions and get different outputs.

```
$ curl https://api.mytest.kubecf.cloud/info |jq
{
  "name": "",
  "build": "",
  "support": "",
  "version": 0,
  "description": "",
  "authorization_endpoint": "https://login.mytest.kubecf.cloud",
  "token_endpoint": "https://uaa.mytest.kubecf.cloud",
  "allow_debug": true
}

$ curl https://api.mytest.kubecf.cloud/v2/info |jq
{
  "name": "",
  "build": "",
  "support": "",
  "version": 0,
  "description": "",
  "authorization_endpoint": "https://login.mytest.kubecf.cloud",
  "token_endpoint": "https://uaa.mytest.kubecf.cloud",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "app_ssh_endpoint": "ssh.mytest.kubecf.cloud:2222",
  "app_ssh_host_key_fingerprint": "5a:ad:18:63:b5:d0:d4:30:fc:03:8c:72:58:3d:14:2a",
  "app_ssh_oauth_client": "ssh-proxy",
  "doppler_logging_endpoint": "wss://doppler.mytest.kubecf.cloud:443",
  "api_version": "2.153.0",
  "osbapi_version": "2.15",
  "routing_endpoint": "https://api.mytest.kubecf.cloud/routing"
}

$ curl https://api.mytest.kubecf.cloud/v3/info |jqt
{
  "build": "",
  "cli_version": {
    "minimum": "",
    "recommended": ""
  },
  "custom": {},
  "description": "",
  "name": "",
  "version": 0,
  "links": {
    "self": {
      "href": "https://api.mytest.kubecf.cloud/v3/info"
    },
    "support": {
      "href": ""
    }
  }
}
```

but I fail to get the point of the issue, what is expect ? @viccuad 

Does it want the same output as `/v2/info` when do `curl http://api.vic-cap.ci.kubecf.charmedquarks.me/info` ?
Or just want to fill the empty parameters 
```
{
  "name": "xxx",
  "build": "xxx",
  "support": "xxx",
  "version": 0,
  "description": "xxxx",
  "authorization_endpoint": "https://login.vic-cap.ci.kubecf.charmedquarks.me",
  "token_endpoint": "https://uaa.vic-cap.ci.kubecf.charmedquarks.me",
  "allow_debug": true
}
```

**Comment by viccuad** [comment]
We want to fill the empty parameters, as they are used for other projects, such as Stratos, to list and interact correctly with KubeCF once it is deployed.

**Comment by andreas-kupries** [comment]
Confirmed in a minikube setup with all of `info`, `v2/info` and `v3/info`, via `cf curl`.

**Comment by andreas-kupries** [comment]
Possible template `capi-release/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb`:
```
info:
  name: "<%= p("name") %>"
  build: "<%= p("build") %>"
  version: <%= p("version") %>
  support_address: "<%= p("support_address") %>"
  description: "<%= p("description") %>"
```
Possible spec `capi-release/jobs/cloud_controller_ng/spec`:
```
  name:
    description: "'name' attribute in the /v2/info endpoint"
    default: ""
  build:
    description: "'build' attribute in the /v2/info endpoint"
    default: ""
  version:
    description: "'version' attribute in the /v2/info endpoint"
    default: 0
  support_address:
    description: "'support' attribute in the /v2/info endpoint"
    default: ""
  description:
    description: "'description' attribute in the /v2/info endpoint"
    default: ""
```
Note the reference to `v2`. It is unclear if `info` is still supported.

Confirmed that this information is not set in the rendered cc_ng yaml config file.

**Comment by andreas-kupries** [comment]
Setting
```
properties:
  api:
    cloud_controller_ng:
      name: "CAP kubecf"
      build: "9999"
      version: "7777"
      support_address: "https://suse.com"
      description: "CAP kubecf, Kubified CloudFoundry"
```
as user-overrides fixes the results returned for the above endpoints.
