### ISSUE TITLE
StatefulSet diego-cell failed on CaaSP-4.*

### ISSUE THREAD

**Issue by svollath** [cloudfoundry-incubator/kubecf#1423]
**Describe the bug**
StatefulSet diego-cell fails on CaaSP4

**To Reproduce**
Install kubecf-2.5.3 onto SUSE CaaSP-4.*

**Expected behavior**
All pods incl. diego-cell do apply/start.

**Environment**
 - SUSE CaaSP-4.2 and CaaSP4.5

**Additional context**
kubectl get events
```
5m31s       Warning   FailedCreate statefulset/diego-cell create Pod diego-cell-0 in StatefulSet diego-cell failed error:
pods "diego-cell-0" is forbidden: unable to validate against any pod security policy:
[spec.initContainers[12].securityContext.privileged: Invalid value: true: Privileged containers are not allowed
spec.initContainers[26].securityContext.privileged: Invalid value: true: Privileged containers are not allowed
pod.metadata.annotations[container.apparmor.security.beta.kubernetes.io/bpm-pre-start-rep]: Forbidden: unconfined is not an
allowed profile. Allowed values: "runtime/default" spec.initContainers[27].securityContext.privileged: Invalid value: true:
Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are
not allowed pod.metadata.annotations[container.apparmor.security.beta.kubernetes.io/rep-rep]: Forbidden: unconfined is not 
allowed profile. Allowed values: "runtime/default" spec.containers[1].securityContext.privileged: Invalid value: true: Privileged
containers are not allowed spec.containers[3].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be
added spec.containers[3].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added
spec.containers[4].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added
spec.containers[4].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added
spec.containers[5].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added
spec.containers[3].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added
spec.containers[3].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added
spec.containers[4].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added
spec.containers[4].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added
spec.containers[5].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added]
```

**Comment by svollath** [comment]
Just to clarify - this is not fixed with kubecf-2.5.4. It's broken, still.

**Comment by jandubois** [comment]
I've reproduced the problem with CaaSP 4.2 using vagrant-caasp and the current kubecf `master` branch.

A simplified repro is creating this stateful set:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pause
spec:
  serviceName: pause
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      serviceAccountName: default
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
```
