### ISSUE TITLE
Can't upgrade(and install) kubecf from 2.2.3 to 2.5.6

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/kubecf#1458]
**Describe the bug**
Upgrading to KubeCF 2.5.6 from KubeCF 2.2.3 (SA in k3s) fails with:

``` 
$> helm upgrade kubecf --namespace kubecf ./kubecf_release.tgz --values ../kubecf-config-values.yaml
Error: UPGRADE FAILED: cannot patch "kubecf" with kind BOSHDeployment: admission webhook "validate-boshdeployment.quarks.cloudfoundry.org" denied the request: Failed to resolve manifest: failed to apply addons: failed to process include placement matches: failed to process match for instance group diego-cell: failed to calculate OS for BOSH job cflinuxfs3-rootfs-setup in instanceGroup diego-cell: release '' not found
```

similarly, @greygoo reported the same error but installing KubeCF 2.5.6 on CaaSP 4.2 (Diego):

```
$> helm3 install kubecf kubecf-bundle-v2.5.6/kubecf --namespace kubecf --values kubecf-config-values_metallb.yaml
Error: admission webhook "validate-boshdeployment.quarks.cloudfoundry.org" denied the request: Failed to resolve manifest: failed to apply addons: failed to process include placement matches: failed to process match for instance group diego-cell: failed to calculate OS for BOSH job cflinuxfs3-rootfs-setup in instanceGroup diego-cell: release '' not found
```

I tried to reproduce on a HA setup, collecting cfo logs with a different error:

```
$> helm upgrade kubecf --namespace kubecf ./kubecf_release.tgz --values ../kubecf-config-values.yaml
Error: UPGRADE FAILED: cannot patch "kubecf" with kind BOSHDeployment: Internal error occurred: failed calling webhook "validate-boshdeployment.quarks.cloudfoundry.org": Post https://cf-operator-webhook.cf-operator.svc:443/validate-boshdeployment?timeout=17s: context deadline exceeded
```

My config values, note external_db is turned off even if values are setted up: 

```yaml
system_domain: 10.86.1.11.nip.io
install_stacks:
  - sle15
credentials:
  cf_admin_password: xx
  uaa_admin_client_secret: xx

features:
  eirini:
    enabled: false
  ingress:
    enabled: true
  embedded_database:
    enabled: true
  external_database:
    enabled: false
    seed: true 
    type: mysql
    host: kubecf-mysql.kubecf-mysql.svc
    port: 3306
    databases:
      uaa:
        name: uaa
        password: test
        username: root
      cc:
        name: cloud_controller
        password: test
        username: root
      bbs:
        name: diego
        password: test
        username: root
      routing_api:
        name: routing-api
        password: test
        username: root
      policy_server:
        name: network_policy
        password: test
        username: root
      silk_controller:
        name: network_connectivity
        password: test
        username: root
      locket:
        name: locket
        password: test
        username: root
      credhub:
        name: credhub
        password: test
        username: root
kube:
  storage_class: local-path

high_availability: true    
```

Quarks operator logs:
[HA - ctx_timeout_error -  cfo-upgrade-kubecf.log](https://github.com/cloudfoundry-incubator/kubecf/files/5341167/cfo-upgrade-kubecf.log)
[HA -  ctx_timeout_error - cfo-upgrade-kubecf-2.log](https://github.com/cloudfoundry-incubator/kubecf/files/5341174/cfo-upgrade-kubecf-2.log)

From the logs, seems there is still trace of `adaptor-0`:

```
cf-operator-bfbdd8fb7-m75sr cf-operator 2020-10-07T13:35:16.684Z	[31mERROR[0m	boshdeployment-reconciler	boshdeployment/deployment_reconciler.go:215	Error resolving the manifest 'kubecf/kubecf': Failed to interpolate "<long-snippet-had-to-cut-see-cfo-upgrade-logs-2.txt" in interpolation task: could not evaluate variables: Expected to find exactly one matching array item for path '/instance_groups/name=adapter' but found 0
cf-operator-bfbdd8fb7-m75sr cf-operator code.cloudfoundry.org/quarks-operator/pkg/kube/controllers/boshdeployment.(*ReconcileBOSHDeployment).resolveManifest
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/src/code.cloudfoundry.org/quarks-operator/pkg/kube/controllers/boshdeployment/deployment_reconciler.go:215
cf-operator-bfbdd8fb7-m75sr cf-operator code.cloudfoundry.org/quarks-operator/pkg/kube/controllers/boshdeployment.(*ReconcileBOSHDeployment).Reconcile
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/src/code.cloudfoundry.org/quarks-operator/pkg/kube/controllers/boshdeployment/deployment_reconciler.go:141
cf-operator-bfbdd8fb7-m75sr cf-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244
cf-operator-bfbdd8fb7-m75sr cf-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218
cf-operator-bfbdd8fb7-m75sr cf-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197
cf-operator-bfbdd8fb7-m75sr cf-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155
cf-operator-bfbdd8fb7-m75sr cf-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156
cf-operator-bfbdd8fb7-m75sr cf-operator k8s.io/apimachinery/pkg/util/wait.JitterUntil
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133
cf-operator-bfbdd8fb7-m75sr cf-operator k8s.io/apimachinery/pkg/util/wait.Until
cf-operator-bfbdd8fb7-m75sr cf-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90
```

**To Reproduce**
Upgrade from 2.2.3 to 2.5.6
