### ISSUE TITLE
External blobstore with object store implemenatations that are compliant with AWS S3 API

### ISSUE THREAD

**Issue by sourirv** [cloudfoundry-incubator/kubecf#1540]
**Is your feature request related to a problem? Please describe.**
Out of the box KubeCF allows the usage of AWS S3 as an external blobstore. There are cases where it would be useful to use S3 API compliant implementations such as MinIO, Ceph etc.

**Describe the solution you'd like**
Perhaps allowing operators to specify a `endpoint-url` in the helm values overrides would help.

**Describe alternatives you've considered**
At the moment an Amazon S3 bucket seems to be the only option for external blobstore.

**Additional context**
For S3 compliant implementations, one typically provides an `endpoint-url` to be able to use S3 API, cli tools or sdks as appropriate.

`aws s3api get-bucket-location --bucket=bucketname --endpoint-url=https://endpoint`

If the implementation of the KubeCF external blobstore uses AWS S3 sdks or APIs, then perhaps allowing one to specify an endpoint url would allow the blobstore to work with other S3 implementations.
My thinking is along the lines of the following pseudo-code for a go s3 client usage ...

```
func newSession() (*session.Session, error) {
    creds := credentials.NewStaticCredentials("<SecretID>", "<SecretKey>", "")
    region := "ap-southeast"
    endpoint := "https://endpoint-url"

    config := &aws.Config{
        Region:           aws.String(region),
        Endpoint:         &endpoint,
        S3ForcePathStyle: aws.Bool(true),
        Credentials:      creds,
        // DisableSSL:       &disableSSL,
    }

    return session.NewSession(config)
}

```

**Comment by jandubois** [comment]
You are in luck; I've just been working on this in #1531  

It is slightly more complex as there are *two* different mechanisms talking to the blobstore; the cloud controller uses the `fog` Ruby gem, and Eirini uses the `bits-service` which has some custom Go component, so any configuration must be able to map to both implementations.

This is still work-in-progress, but I've already connected to a MinIO instance as external blobstore with both Diego and Eirini.

**Comment by sourirv** [comment]
@jandubois thanks for the follow up.
Just FYI, for diego deployments, for now I created a "work around" to get the external blobstore working with an S3 compliant (non AWS) implementation.
Here's what I did as the workaround and it works for me ...

1) Defined a secret in `s3-blobstore.yml` like so ...

```
---
apiVersion: "v1"
kind: "Secret"
type: Opaque
metadata:
  name: var-endpoint-url
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
stringData:
  value: "{{ .Values.features.blobstore.s3.endpoint_url }}"
```

2) Edited `use-s3-blobstore.yml` to reference `endpoint_url` like so ...

```
---
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks/fog_connection
  error: "Please apply 'use-external-blobstore.yml' before applying 'use-s3-blobstore.yml'."
  value: &blobstore-properties
    provider: AWS
    aws_access_key_id: ((blobstore_access_key_id))
    aws_secret_access_key: ((blobstore_secret_access_key))
    region: ((aws_region))
    endpoint: ((endpoint_url))
```

3) Used the following variable overrides in my values.yaml for helm install ...

```
features:
  blobstore:
    provider: s3
    s3:
      aws_region: ap-some_region
      endpoint_url: S3_ENDPOINT
      blobstore_access_key_id: AKISOMETHING
      blobstore_secret_access_key: dLoMekSOMETHING
      blobstore_admin_users_password: ~
      app_package_directory_key: sourirv-bucket
      buildpack_directory_key: sourirv-bucket
      droplet_directory_key: sourirv-bucket
      resource_directory_key: sourirv-bucket
```

Specifying a valid value for S3_ENDPOINT, allows the diego-cell and api pods to come up successfully and also creates a bunch of folders on the bucket, just like it does with an AWS S3 bucket.
