### ISSUE TITLE
Mechanism to bump the defaults stemcell version in kubecf

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#172]
The default values for the stemcell `os` and `version` are currently defined here:

https://github.com/SUSE/kubecf/blob/0f374044d1a86f27d1f9c0b3ba88137e785ad413/deploy/helm/kubecf/values.yaml#L20-L26

Since `kubecf` pipelines must use the images built with the latest available stemcell version so there needs to be a separate pipeline in order to bump the stemcell version in `kubecf` repo as soon as there is a new release. The pipeline can make use of the following config:

https://github.com/SUSE/cf-ci/blob/75aea2a2e55d865a38556a861584b71a682f6474/kubecf-build-pipelines/release-images-cf-deployment/config.yml#L13-L16

Also, the [buildpacks` ops file](https://github.com/SUSE/kubecf/blob/0f374044d1a86f27d1f9c0b3ba88137e785ad413/deploy/helm/kubecf/assets/operations/buildpacks/set_suse_buildpacks.yaml) should be modified to use the following structure in order to make the stemcell version consistent across all releases: 

```
- type: replace
  path: /releases/-
  value:
    name: suse-binary-buildpack
    url: registry.suse.com/cap-staging
    version: "1.0.33.1"
    stemcell:
      os: {{ default (index .Values.releases "suse-binary-buildpack").stemcell.os .Values.releases.defaults.stemcell.os | quote }}
      version: ...
```
**Note:** These changes have to be co-ordinated between upstream and suse pipelines.
