### ISSUE TITLE
CATS: Properties not working as expected.

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#187]
**Describe the bug**
Setting following properties in `values.yaml` is expected run only `internetless` CATs suite, however in practice I have noticed it running `apps` suite in addition to `internetless`. This issue might not be specific to running any particular suite.

```
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        include: '=internetless'
```

**To Reproduce**
Set above properties in your `values.yaml` and run CATs: `bazel run //testing/acceptance_tests`

**Expected behavior**

**Environment**
 - Component/Plugin Name: CATs
