### ISSUE TITLE
Test & document using an external blobstore

### ISSUE THREAD

**Issue by gaktive** [cloudfoundry-incubator/kubecf#200]
**Is your feature request related to a problem? Please describe.**
Within the CF ecosystem, the blobstore is a single point of failure since only one can exist. Let's find out what's needed to support an external blobstore.

https://docs.cloudfoundry.org/deploying/common/cc-blobstore-config.html

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by troytop** [comment]
According to @jandubois the config would be inserted in a block like this:

```
bosh:
  instance_groups:
  - name: cc-worker
    jobs:
    - name: cloud_controller_worker
      properties:
        cc:
          ....
```
