### ISSUE TITLE
CCDB encryption key rotation breaks on second rotation

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#524]
Filed by @hartS 

I noticed this when I originally tested ccdb secret rotation and thought it was an intermittent issue, but after some more testing, it appears that the CCDB secret rotation breaks a kubecf deployment when performed a second time.

To repro:

After deploying kubecf, the ccdb secret can be rotated following this document, by upgrading the helm release and providing values that look like:
```ccdb:
  encryption:
    rotation:
      key_labels:
      - encryption_key_0
      - encryption_key_1
      current_key_label: encryption_key_1
```
After the kubecf deployment is ready again, the rotation can be triggered again by providing values like:
```
ccdb:
  encryption:
    rotation:
      key_labels:
      - encryption_key_0
      - encryption_key_1
      - encryption_key_2
      current_key_label: encryption_key_2
```
After attempting to rotate the secret a second time, the kubecf cluster will never recover. The status column for the api pod will show containers initializing, eventually counting up to Init:31/63 . The count will stall here for 2-3 minutes and then go into an Init:CrashLoopBackOff} or {{Init:Error state before attempting to initialize pods in the container again.

Tested with SA deployments on the latest nightly ( dd25a5e ) as well as older kubecf builds.
