### ISSUE TITLE
Allow the user to define CATs tests to run or to not run

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#594]
**Is your feature request related to a problem? Please describe.**
Yes, there is no flexibility during run time(installation/upgrade) to define the CATs test to run.

**Describe the solution you'd like**
A feature flag that can hold a list of test to skip or to run

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by f0rmiga** [comment]
We can extend:
https://github.com/cloudfoundry-incubator/kubecf/blob/2cf693c261b95fbb5f32e56f392876b8bea30390/deploy/helm/kubecf/values.yaml#L311-L319

instead of adding another feature flag. For now, you can achieve that with:

```yaml
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        include: '=ssh'
        ginkgo:
          nodes: 12
          extra_flags: -v
          flake_attempts: 2
```

(I added the `ginkgo` key above as an example of how to also tweak it)
