### ISSUE TITLE
Allow the user to parameterized ClusterRole rules resources for Eirini

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#595]
**Is your feature request related to a problem? Please describe.**
Yes, there is no way to extend the resources rules in https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/templates/eirini.yaml#L12 , unless you apply a manual change or a patch of the file. For some IaaS, the resources list requires more items.

**Describe the solution you'd like**
A feature flag in the values.yml

**Describe alternatives you've considered**
None

**Additional context**
Yes, in IKS, we required to have the following resources:
```
resources: ['mutatingwebhookconfigurations', 'nodes', 'nodes/proxy']
```

**Comment by f0rmiga** [comment]
+1 to this, but instead of modifying _that_ ClusterRole, which is tied to the webhook, we should have a different ClusterRole which indicates the extra values provided by the user.

**Comment by qu1queee** [comment]
@f0rmiga ok, I will assign this to someone from IBM, to help here

**Comment by EmilyEmily** [comment]
@qu1queee I can take this issue, but I haven't authority to assign it to me, could you help? Thanks.

**Comment by EmilyEmily** [comment]
@qu1queee @f0rmiga , can we name the feature flag to "customresource"? 
Do we need flexibility that allows user to specify it's own customresource besides IKS' requirement
```
resources: ['mutatingwebhookconfigurations', 'nodes', 'nodes/proxy']
```

If yes, then I'll add additional parameter for this feature flag, like this way: 
```
features:
  customresource:
    enabled: true
    resource: "'mutatingwebhookconfigurations', 'nodes', 'nodes/proxy'"
```

If no, then the feature flag is simply with the enabled parameter. 
```

**Comment by f0rmiga** [comment]
@EmilyEmily Since this is tied to Eirini, it shouldn't be a separate feature flag.

I see it being:

```yaml
features:
  eirini:
    rbac:
      cluster_role:
        rules:
        - apiGroups: ['admissionregistration.k8s.io']
          resources: ['nodes', 'nodes/proxy']
          verbs:     ['*']
```

Then you generate a new block conditionally:

```yaml
{{- if <check that the user provided extra stuff> }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:eirini-webhook-user-provided
rules:
{{ .Values.features.eirini.rbac.cluster_role.rules | toYaml }}
{{- end }}
```

This is a rough draft... completely untested but showing the logic.

You will also need to do some templating for binding the ClusterRole to the Eirini ServiceAccount.
