### ISSUE TITLE
EiriniX crashed after applying a change to values.yaml

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#729]
**Describe the bug**

Logs from `eirini-loggregator-bridge-eirini-loggregator-bridge`:
```
{"level":"info","ts":1587421772.3172147,"caller":"config/getter.go:53","msg":"Using in-cluster kube config"}
{"level":"info","ts":1587421772.3172426,"caller":"config/checker.go:36","msg":"Checking kube config"}
Received non-pod object in watcher channel
Watcher channel closed
```

**To Reproduce**

1. Deploy with Eirini.
2. Apply a change to `values.yaml`, in my case, I changed the number of nodes on CATS:
From:
```yaml
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        ginkgo:
          nodes: 6
```
To:
```yaml
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        ginkgo:
          nodes: 1
```

After the KubeCF installation gets updated, Eirini crashes.

**Expected behavior**

Eirini should not crash.

**Environment**

Tip of `master`.
