### ISSUE TITLE
TLS secrets for the embedded database should be plain k8s resources

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#772]
**Describe the bug**

Currently, the TLS secrets are created via the BOSH variables, which doesn't make sense in our current setup that the database is a standalone PXC Helm chart.

**To Reproduce**

Go to the chart templates and assert that we don't create the TLS secrets there.

**Expected behavior**

The TLS secrets should be created together with the other database k8s resources.

**Comment by viovanov** [comment]
These should be `QuarksSecrets`

**Comment by andreas-kupries** [comment]
@f0rmiga @viovanov With regard to the TLS variables we want to be gone, are we talking about

```yaml
# Add certificates for PXC.
- type: replace
  path: /variables/-
  value:
    name: pxc_ca
    type: certificate
    options:
      common_name: pxc_ca
      is_ca: true
- type: replace
  path: /variables/-
  value:
    name: pxc_tls
    type: certificate
    options:
      ca: pxc_ca
      common_name: &pxc-cluster-address {{ printf "database.%s" .Release.Namespace }}
```

in file `kubecf/assets/operations/instance_groups/database.yaml` ?

Musings ...
- I notice that the above contains the anchor `&pxc-cluster-address`, and that further down in the same file this anchor is used. This seems to be fixable with a helper key in the ops file.
- Further however is the use of the BOSH variable `((pxc_tls.ca))` ... Ah, that likely maps to the value of `options.ca`, i.e. `pxc_ca`, and that is then used via anchor, so just another helper key.
- Hm. ... Ah, the eirini template has example of a `QS` for a certificate. And should be able to derive CA cert as well.
