### ISSUE TITLE
EiriniX Persi init container requires root

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#782]
In [`VcapServices.AppendMounts()`] we create an init container that needs to run as root (to run `chmod` to ensure the mount has the correct permissions). However, [`StatefulSetDesirer.getGetSecurityContext()`] can (at least in the cases I tested) end up with a security context of `runAsNonRoot: true`.

This leads to the pod not starting, with an error message of `Error: container's runAsUser breaks non-root policy`.

[`VcapServices.AppendMounts()`]: https://github.com/SUSE/eirini-persi/blob/2074eb02955953e77b4c20855a8ed1ced4808318/extensions/persistence/persistence.go#L71-L72
[`StatefulSetDesirer.getGetSecurityContext()`]: https://github.com/cloudfoundry-incubator/eirini/blob/1.5.0/k8s/statefulset.go#L609

**Comment by viovanov** [comment]
We should try to also mutate `fsGroup` as mentioned here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#podsecuritycontext-v1-core

also see https://github.com/kubernetes/kubernetes/issues/2630

**Comment by jandubois** [comment]
> We should try to also mutate `fsGroup` as mentioned here:

This didn't work for me. I've added `FSGroup: 2000` to the PodSecurityContext, and removed `RunAsUser: 0` from the initContainer SecurityContext:

```
apiVersion: v1
kind: Pod
spec:
  containers:
  - command:
    - dumb-init
    securityContext:
      allowPrivilegeEscalation: false
  initContainers:
  - command:
    - sh
    - -c
    - chown -R vcap:vcap /var/vcap/data/e31ef38c-c6e6-41ec-95b5-4fb4df5f15b6
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
status:
  containerStatuses:
  - state:
      waiting:
        reason: PodInitializing
  initContainerStatuses:
  - lastState:
      terminated:
        exitCode: 1
        reason: Error
    ready: false
    restartCount: 3
    state:
      waiting:
        message: Back-off 40s restarting failed container=eirini-persi-1e966101-ba04-4472-9677-7a029630d7a5
          pod=12factor-myspace-770ddd1012-0_eirini(095543b3-0ace-4cd2-8bee-48f92d907b94)
        reason: CrashLoopBackOff
```

`vcap` uid and gid are both `2000`.

But the initContainer still throws an error:

```
chown: changing ownership of '/var/vcap/data/e31ef38c-c6e6-41ec-95b5-4fb4df5f15b6': Operation not permitted
```

@viovanov Is there something else to try, or do we need to ask for permission to run as root?
