### ISSUE TITLE
Control plane feature

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#936]
**Is your feature request related to a problem? Please describe.**
A feature to enable `control-plane` mode.

**Describe the solution you'd like**
When the control plane feature is enabled, the `cluster-worker` cannot be enabled.
The user should be allowed to specify an array of cluster workers to be registered as services.

e.g. 
```
features:
  control-plane:
    enabled: true
    workers:
    - name: minions-1-diego-cell-0
      address: 172.22.216.231
```

See sample here: https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-50ef3ab48d651f63f084a6815a7115d1

When the `control-plane` feature is enabled, the following ops file must be activated, to remove cells from the control plane:

https://github.com/cloudfoundry-incubator/kubecf/commit/b50a8c8de46e681505621108c440eabd424c469f#diff-8fc2de7ef5a3d25ddfce0cd023890d0cR987-R989

**Describe alternatives you've considered**
n/a

**Additional context**
#822
