### ISSUE TITLE
Expose <role>.cpu|memory.request|limit in values.yaml

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#955]
In scf it was possible to set memory and CPU requests and limits for each CF role via helm. It's not clear if this is possible in KubeCF. This needs to be exposed.

If this is possible currently, there should be some indication in the Helm chart `values.yaml` how these can be set.

**Comment by jandubois** [comment]
It is currently possible (via quarks-operator) to set memory limits on containers, but not on roles (instance groups).

This requires a custom ops-file and knowledge about the jobs and processes in each instance group, e.g.

```
operations:
  inline:
  - type: replace
    path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/quarks?/bpm/processes/name=log-cache/limits/memory
    value: 2G
```

As requested, we should provide a helm mechanism to set these limits.

It is not possible to set CPU limits. This would have to be implemented in Quarks first.

Question: do we also need to be able to set limits on pre-start scripts, or only on the long-running processes?
